//ST10281011 Akhilesh Parshotam
package st10281011_prog5121_poe_part_3;

import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author ST10281011 Akhilesh Parshotam
 */
public class Task 
{

    // Method to check if the Task Description meets the length requirements.
    public static boolean checkTaskDescription(String[] Task_Descriptions) 
    {
        for (String T_Descrip : Task_Descriptions) 
        {
            if (T_Descrip.length() > 50) 
            {
                return false;
            }
        }
        return true;
    }

    //********************************************************************************************************************************
    
    //Attribution for ArrayLists https://www.w3schools.com/java/java_arraylist.asp
    
    // Method that prompts the user to enter all the information needed for each task.
    public static void addTasks(ArrayList<Integer> Task_Numbers, ArrayList<String> Task_Names, ArrayList<String> Task_Descriptions, 
            ArrayList<String> Developers_First_Names, ArrayList<String> Developers_Last_Names, ArrayList<Integer> Task_Durations, 
            ArrayList<String> Task_IDs, ArrayList<String> Task_Statuses, ArrayList<Integer> Total_Hours) 
    {
        
        //Promts the user to enter the number of tasks they would like to enter.
        int Num_Tasks = Integer.parseInt(JOptionPane.showInputDialog("Enter the number of tasks you would like to add:"));

        //For loop that will loop through each task prompting for all the task details.
        for (int i = 0; i < Num_Tasks; i++) 
        {
            Task_Numbers.add(i);// Assigning the task number. the task number is autogenerated and increments on its own.
            
            //Prompts the user to enter the name of the task.
            Task_Names.add(JOptionPane.showInputDialog("Enter the task name:"));

            //Prompts the user to enter the developers first and last name.
            Developers_First_Names.add(JOptionPane.showInputDialog("Enter the developer's first name:"));
            
            Developers_Last_Names.add(JOptionPane.showInputDialog("Enter the developer's last name:"));

            //Promps the user to enter the expected duration for the task.
            Task_Durations.add(Integer.valueOf(JOptionPane.showInputDialog("Enter the task duration in hours:")));

            /*
            Calling the createTaskID method. the Task ID is autogenerated and includes the task name, task number and 
            the developers first name.
            */
            Task_IDs.add(createTaskID(Task_Names.get(i), Task_Numbers.get(i), Developers_First_Names.get(i)));

            //Attribution for a Drop down menu https://www.tutorialspoint.com/swingexamples/show_input_dialog_list.htm.
            
            //The options for the tasck stauts stored in an array.
            String[] Task_Status_Options = {"To Do", "Done", "Doing"};
            
            //Prompting the user to select an option for the task status from the options array.
            Task_Statuses.add((String) JOptionPane.showInputDialog(null, "Select task status:",
                            "Task Status",JOptionPane.PLAIN_MESSAGE, null, Task_Status_Options, Task_Status_Options[0]));

            /*
            A while loop that prompts the user to enter the task description that meets the length requirments. Displaying the 
            appropriate messaging when the the task description is inputed correctly and when the task description is 
            inputted incorrectly. 
            */
            while (true) 
            {
                //Prompts the user to enter the task description.
                String T_Descrip = JOptionPane.showInputDialog("Enter the task description (less than 50 characters):");
                if (checkTaskDescription(new String[]{T_Descrip}))
                {
                    JOptionPane.showMessageDialog(null, "Task successfully captured");
                    Task_Descriptions.add(T_Descrip);
                    break;
                } 
                else 
                {
                    JOptionPane.showMessageDialog(null, "Please enter a task description of less than 50 characters");
                }
            }
            
            //Calling the print printTaskDetails method.
            String Task_Details = printTaskDetails(Task_Numbers.get(i), Task_Names.get(i), Task_Descriptions.get(i), 
                    Task_Durations.get(i), Task_IDs.get(i), Task_Statuses.get(i), Developers_First_Names.get(i), 
                    Developers_Last_Names.get(i));
            
            //Displaying the task Details.
            JOptionPane.showMessageDialog(null, Task_Details);

            //Calling the returnTotalHours method. 
            Total_Hours.add(returnTotalHours(Task_Durations.get(i), Total_Hours));
        }

        int Tot_Hours = 0;
        for (int Hours : Total_Hours) 
        {
            Tot_Hours += Hours;
        }
        //Displaying the total combined hours of all tasks.
        JOptionPane.showMessageDialog(null, "Total combined hours of all tasks: " + Tot_Hours + " hrs");
    }
    
    //*******************************************************************************************************************************

    // Method that creates the task ID using the task name, task number, and the developer's first name.
    public static String createTaskID(String T_Name, int T_Num, String Dev_F_Name) 
    {
        /*
        Creating the task ID using the first 2 letters of the task name, the last 3 letters of the develepers first name
        (done using string manipulation)and the tack number which is autogenerated.
        */
        return T_Name.substring(0, 2).toUpperCase() + ":" + T_Num + ":" + Dev_F_Name.substring(Dev_F_Name.length() - 3).toUpperCase();
    }
    
    //********************************************************************************************************************************

    // Method that defines the structure in which the task details will be displayed.
    public static String printTaskDetails(int T_Num, String T_Name, String T_Descrip, int T_Dur, String T_ID, String T_Status, 
            String Dev_F_Name, String Dev_L_Name) 
    {
        return "Task Status: " + T_Status + "\n" 
                + "Developer Details: " + Dev_F_Name + " " + Dev_L_Name
                + "\n" + "Task Number: " 
                + T_Num + "\n" + "Task Name: "
                + T_Name + "\n" + "Task Description: "
                + T_Descrip + "\n" + "Task ID: " 
                + T_ID + "\n" + "Duration: "
                + T_Dur + " hours";
    }
    
    //********************************************************************************************************************************

    // Method that calculates the total combined hours of all tasks.
    public static int returnTotalHours(int T_Dur, ArrayList<Integer> Total_Hours) 
    {
        int Total = 0;
        for (int Hours : Total_Hours) 
        {
            Total += Hours;
        }
        return Total + T_Dur;
    }
    
    //********************************************************************************************************************************

    // Method that displays tasks with a the task Status of Done.  
    public static ArrayList<String> displayTasksWithStatus(ArrayList<String> Task_Statuses, String T_Status, 
            ArrayList<String> Developer_First_Names, ArrayList<String> Developer_Last_Names, ArrayList<String> Task_Names,
            ArrayList<Integer> Task_Durations) 
    {
            ArrayList<String> All_Done_Tasks = new ArrayList<>();

        for (int i = 0; i < Task_Statuses.size(); i++) 
        {
            // Check if the current task status matches the task Status of Done
            if (Task_Statuses.get(i).equals(T_Status)) 
            {
                String T_Details = "Developer: " + Developer_First_Names.get(i) + " " + Developer_Last_Names.get(i)
                        + "\nTask Name: " + Task_Names.get(i)
                        + "\nDuration: " + Task_Durations.get(i) + " hours";

                // Add the task details to the matchingTasks ArrayList
                All_Done_Tasks.add(T_Details);
            }
        }
        if (All_Done_Tasks.isEmpty()) 
        {
            All_Done_Tasks.add("No tasks found with the status: " + T_Status);
        }

        return All_Done_Tasks;
    }
    
     //*******************************************************************************************************************************
    
    // Method that displays the task that has the longist duration.
    public static String displayTaskWithLongestDuration(ArrayList<String> Developers_First_Names, 
            ArrayList<String> Developers_Last_Names, ArrayList<Integer> Task_Durations) 
    {
        int Max_Dur = 0;
        int Max_Dur_Index = -1;

        // Find the index of the task with the longest duration.
        for (int i = 0; i < Task_Durations.size(); i++) 
        {
            if (Task_Durations.get(i) > Max_Dur) 
            {
                // Updates the maxium duration and its index.
                Max_Dur = Task_Durations.get(i);
                Max_Dur_Index = i;
            }
        }

        if (Max_Dur_Index != -1) 
        {
            String Dev_F_Name = Developers_First_Names.get(Max_Dur_Index);
            String Dev_L_Name = Developers_Last_Names.get(Max_Dur_Index);

            // Display the developer name and duration of the task with the longest duration
            return "Developer: " + Dev_F_Name + " " + Dev_L_Name 
                    + "\nDuration: " + Max_Dur + " hours";
        } 
        else 
        {
            return "No tasks found";
        }
    }
    
    //********************************************************************************************************************************

    // Method that seaches for a task by the task name.
    public static String searchTaskByTaskName(ArrayList<String> Task_Names, ArrayList<String> Developers_First_Names, 
            ArrayList<String> Developers_Last_Names, ArrayList<String> Task_Statuses, String Search_T_Name)
    {
        for (int i = 0; i < Task_Names.size(); i++) 
        {
            // Check if the task name is the same as the task name you want to search for. 
            if (Task_Names.get(i).equalsIgnoreCase(Search_T_Name)) 
            {
                String T_Name = Task_Names.get(i);
                String Dev_F_Name = Developers_First_Names.get(i);
                String Dev_L_Name = Developers_Last_Names.get(i);
                String T_Status = Task_Statuses.get(i);

                // Display the task name, developer name and task status of the task that was search for.
                return "Task Name: " + T_Name 
                        + "\nDeveloper: " + Dev_F_Name + " " + Dev_L_Name 
                        + "\nTask Status: " + T_Status;
            }
        }
        return "No tasks found with the task name " + Search_T_Name;
    }
    
    //********************************************************************************************************************************

    public static ArrayList<String> searchTasksByDeveloperName(ArrayList<String> Task_Names, ArrayList<String> Developers_First_Names,
            ArrayList<String> Developers_Last_Names, ArrayList<String> Task_Statuses, String Search_Dev_Full_Name) 
    {
        ArrayList<String> Tasks_By_Dev = new ArrayList<>();

        for (int i = 0; i < Developers_First_Names.size(); i++) 
        {
            String Full_Name = Developers_First_Names.get(i) + " " + Developers_Last_Names.get(i);

            // Check if the developer's full name matches the search name
            if (Full_Name.equalsIgnoreCase(Search_Dev_Full_Name)) 
            {
                String T_Name = Task_Names.get(i);
                String T_Status = Task_Statuses.get(i);

                // Create a string with the task name and task status of the matched task
                String T_Details = "Task Name: " + T_Name + "\nTask Status: " + T_Status;

                // Add the task details to the matchingTasks ArrayList
                Tasks_By_Dev.add(T_Details);
            }
        }
        if (Tasks_By_Dev.isEmpty()) 
        {
            Tasks_By_Dev.add("No tasks found for the developer " + Search_Dev_Full_Name);
        }

        return Tasks_By_Dev;
    }
    
    //********************************************************************************************************************************

    // Method that deletes a task by the task name.
    public static String deleteTaskByTaskName(ArrayList<String> Task_Names, ArrayList<String> Developers_First_Names, 
            ArrayList<String> Developers_Last_Names, ArrayList<String> Task_Statuses, String Del_T_Name)
    {
        for (int i = 0; i < Task_Names.size(); i++) 
        {
            //Checks if the task name is the same as the task  you want to delete
            if (Task_Names.get(i).equalsIgnoreCase(Del_T_Name)) 
            {
                Task_Names.remove(i);
                Developers_First_Names.remove(i);
                Developers_Last_Names.remove(i);
                Task_Statuses.remove(i);

                // Display a return message.
                return "Task deleted successfully";
            }
        }
        return "Task not found";
    }
    
    //********************************************************************************************************************************

    // Method that displays all the tasks that were entered.
    public static ArrayList<String> displayAllTasks(ArrayList<Integer> Task_Numbers, ArrayList<String> Task_Names, 
            ArrayList<String> Task_Descriptions, ArrayList<String> Developers_First_Names, ArrayList<String> Developers_Last_Names, 
            ArrayList<Integer> Task_Durations, ArrayList<String> Task_IDs, ArrayList<String> Task_Statuses, 
            ArrayList<Integer> Total_Hours) 
    {
        ArrayList<String> All_Tasks = new ArrayList<>();

        // Check if there are any tasks captured
        if (Task_Names.isEmpty()) 
        {
            All_Tasks.add("No tasks captured.");
        } 
        else 
        {
            // Iterates over  all the tasks and add their details to the ArrayList
            for (int i = 0; i < Task_Names.size(); i++) 
            {
                int T_Num = Task_Numbers.get(i);
                String T_Name = Task_Names.get(i);
                String T_Descrip = Task_Descriptions.get(i);
                int T_Dur = Task_Durations.get(i);
                String T_ID = Task_IDs.get(i);
                String T_Status = Task_Statuses.get(i);
                String Dev_F_Name = Developers_First_Names.get(i);
                String Dev_L_Name = Developers_Last_Names.get(i);

                /*
                Display the task status, developer name, task number, task name, task description, task ID and task 
                duration of all the tasks.
                */
                String T_Details = "Task Status: " + T_Status + "\n"
                        + "Developer Details: " + Dev_F_Name + " " + Dev_L_Name + "\n"
                        + "Task Number: " + T_Num + "\n"
                        + "Task Name: " + T_Name + "\n"
                        + "Task Description: " + T_Descrip + "\n"
                        + "Task ID: " + T_ID + "\n"
                        + "Duration: " + T_Dur + " hours";

                All_Tasks.add(T_Details);
            }
        }
        return All_Tasks;
    }
}
//ST10281011 Akhilesh Parshotam
